name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 3.7.0
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  intl: ^0.20.2


dev_dependencies:
  test: ^1.25.15
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.4
